/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.34
 * Generated at: 2021-01-17 14:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" \t<meta charset=\"UTF-8\">\r\n");
      out.write(" \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write(" \t<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\t<title>Network Commands Simulator</title>\r\n");
      out.write("\r\n");
      out.write(" \t<!-- Font Icon -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fonts/material-icon/css/material-design-iconic-font.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"vendor/jquery-ui/jquery-ui.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Main css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        \r\n");
      out.write("         <div class=\"header\" style=\"padding-left: 90px;padding-top: 80px; ;\">\r\n");
      out.write("             <img src=\"images/CN-1.png\" alt=\"\"> \r\n");
      out.write("             <!-- <img src=\"images/header-text.png\" alt=\"\">  -->\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <form id=\"command-form\" class=\"command-form\" action = \"PingCmd\" method=\"get\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-pingurl\">\r\n");
      out.write("                        <label for=\"pingurl\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"pingurl\" name=\"pingurl\" placeholder=\"Enter URL to ping\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"ping\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-tracerturl\">\r\n");
      out.write("                        <label for=\"tracerturl\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"tracerturl\" name=\"tracerturl\" placeholder=\"Enter URL to trace route\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"tracert\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-nslookupurl\">\r\n");
      out.write("                        <label for=\"nslookupurl\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"nslookupurl\" name=\"nslookupurl\" placeholder=\"Enter URL to lookup\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"nslookup\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-pathpingurl\">\r\n");
      out.write("                        <label for=\"pathpingurl\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"pathpingurl\" name=\"pathpingurl\" placeholder=\"Enter URL to ping the path\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"pathping\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-ipconfig\">\r\n");
      out.write("                        <!-- <label for=\"ipconfig\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"ipconfig\" name=\"ipconfig\" placeholder=\"Enter URL to nslookup\" /> -->\r\n");
      out.write("                        <p><b>FOR IP CONFIG</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"ipconfig\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-getmac\">\r\n");
      out.write("                        <!-- <label for=\"getmac\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"getmac\" name=\"getmac\" placeholder=\"Enter URL to nslookup\" /> -->\r\n");
      out.write("                        <p><b>FOR GETMAC</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"getmac\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"form-netstat\">\r\n");
      out.write("                        <!-- <label for=\"netstat\">URL</label>\r\n");
      out.write("                        <input type=\"text\" id=\"netstat\" name=\"netstat\" placeholder=\"Enter URL to nslookup\" /> -->\r\n");
      out.write("                        <p><b>FOR NETSTAT</b></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-Options\"> \r\n");
      out.write("                        <label for=\"Options\">Option</label> \r\n");
      out.write("                        <input type=\"text\" id=\"Options\" class=\"Options\" placeholder=\"If required\" />\r\n");
      out.write("                        \r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"form-submit\">\r\n");
      out.write("                        <input type=\"submit\" onClick=\"document.getElementById('bottom').scrollIntoView();\" name=\"command\" id=\"submit\" class=\"submit\" value=\"netstat\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"bottom\" >\r\n");
      out.write("        <div>\r\n");
      out.write("            <p id=\"end\">RESPONSE:</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");

String output = request.getParameter("done");
if(output != null){
	for(String line: output.split("\n")){
		
      out.write("\r\n");
      out.write("\t\t<p>");
      out.print(line);
      out.write("</p>\r\n");
      out.write("\t\t");

	}
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JS -->\r\n");
      out.write("    <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"vendor/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
